/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab6;
import java.util.*;
import java.io.*;
public class Components {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        File f = new File(args[0]);
        Scanner sc = new Scanner(f);
        int size = sc.nextInt();
        int[][] vals = new int[size][size];
         for(int i = 0; i < size; i++){
            for(int j = 0; j < 2; j++){
                int a = sc.nextInt();
                int b = sc.nextInt();
                vals[a][b] = 1; 
            }
         }
        int connected = 0;
        ArrayList visited = new ArrayList<Integer>();
        for(int i = 0; i < size; i++){
            if(visited.contains(i)){
                continue;
            }
            connected++;
            for(int j = 0; j < size; j++){
                if(vals[i][j] == 1){
                    visited = goThroughList(i, j, visited, vals, size);
                    System.out.println(visited.toString());
                }
            }
        }
        System.out.println(connected);

    }
    private static ArrayList goThroughList(int i, int j, ArrayList visited, int[][] vals, int size){
        visited.add(j);
        for(int p = 0; p < size; p++){
            if(vals[p][j] == 1 && !visited.contains(p)){
                visited.add(p);
                visited = goThroughList(j, p, visited, vals, size);
            }
        }
        for(int q = 0; q < size; q++){
            if(vals[j][q] == 1){
                if(!visited.contains(q)){
                    visited = goThroughList(j, q, visited, vals, size);
                }
            }
        }
        for(int p = 0; p < size; p++){
            if(vals[p][j] == 1 && !visited.contains(p)){
                visited = goThroughList(j, p, visited, vals, size);
            }
        }
        return visited;
    }
}
